version: '3'

services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ${PWD}/docker/nginx/sites:/etc/nginx/conf.d
      - ${PWD}/symfony:/var/www/app
    links:
      - php:php
      - mysql:mysql
      - redis:redis
    ports:
      - "127.0.0.1:8080:80"

  php:
    build: docker/php
    restart: always
    volumes:
      - ${PWD}/symfony:/var/www/app
      - ${PWD}/docker/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - mysql:mysql
      - redis:redis
      
  mysql:
    restart: always
    image: mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - $PWD/docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      
  redis:
    image: redis
    restart: always
    volumes:
      - ${PWD}/docker/redis/data:/data
    ports:
      - "6379:6379"
